name: Node

on:
  - push
  - pull_request

jobs:
  node:
    name: Checking for problems

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14.x

      - name: 'Install'
        run: yarn install --immutable --immutable-cache --check-cache
        shell: bash

      - name: 'Dedupe'
        run: yarn dedupe --check
        shell: bash

      - name: 'Type-Check'
        run: yarn type-check
        shell: bash

      - name: 'Format'
        run: yarn format
        shell: bash

      - name: 'Lint'
        run: yarn lint
        shell: bash

      - name: 'Build'
        run: yarn build
        shell: bash

      - name: 'Test'
        run: yarn test
        shell: bash
